[general]
page_title = "N0YEP's Log"
database_location = "path_to_log_file.mdb"
output_dir = "path_for_output_file"
output_filename = "log.html"
stylesheet = "/CSS/default.css"

[table_columns]
fldBand = "Band"
fldCall = "Call"
fldMode = "Mode"
fldRstR = "S"
fldRstS = "R"
fldSPCNum = "Country"
fldDateStr = "Date"
fldTimeOnStr = "Time"
